version: "3"
services: 
  postgres:
    image: "postgres:11-alpine"
  redis:
    image: "redis:5-alpine"
  nginx:
    build: 
      dockerfile:  Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
    restart: always
    depends_on: 
      - api
      - client
  api:
    build:
      dockerfile: Dockerfile.dev    
      context: ./api
    volumes:
      - /usr/app/node_modules
      - ./api:/usr/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGHOST=postgres
      - PGPORT=5432
      - PGDATABASE=postgres
      - PGUSER=postgres
      - PGPASSWORD=postgres_password
    depends_on: 
      - postgres
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379